import Head from 'next/head'
import Image from 'next/image'
import Hot from '../components/product/index'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      {/* 本頁面不刻意用container包住，因為container會有padding，會影響到圖片的寬度 */}
      <Head>
        <title>COFFSEEKER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* 此處製作首頁幻燈片 */}
      <div className="img-container">
        <Image
          className="img-fluid ed-position-relative"
          src="http://localhost:3000/index-image/banner-father'sDay.png"
          alt=""
          width={1920}
          height={780}
          id="banner-image"
        />
        <Image
          className="img-fluid ed-position-absolute"
          src="http://localhost:3000/index-image/activity_01.png"
          alt=""
          width={600}
          height={200}
          id="activity-image"
        />
      </div>
      {/* 此處製作商城與課程的按鈕 */}
      <div className="d-md-flex d-flex-colum justify-content-center">
        <a href="http://localhost:3000/product">
          <img
            className="ed-img-size-1"
            src="http://localhost:3000/index-image/product.png"
            alt="go-to-product"
          />
        </a>
        <a href="http://localhost:3000/course">
          <img
            className="ed-img-size-2"
            src="http://localhost:3000/index-image/course.png"
            alt="go-to-course"
          />
        </a>
      </div>
      {/* 此處從後端專取熱銷商品，並提供前八名的商品資訊 */}
      <div className='container'>
        <Hot />
      </div>
      {/* 此處放置團體購買的圖片 */}
      <div className="img-container">
        <img
          className="img-fluid d-block"
          src="http://localhost:3000/index-image/company-buy.png"
          alt=""
          id="company-buy"
        />
      </div>
    </>
  )
}
